// app/ui/components/battle/palette-pool.js — CB-BUILD-006/§18: the
// canonical wizard colour pool, per portrait colour slot. GENERATED by
// sampling 448 real 2019 wizard portraits (the bucket's <contract>/
// <tokenId>.svg files) and collecting every value each CSS colour-slot
// custom property (--hat-base, --hat-accent, --medallion-base,
// --collar-base, --cape-base, --pants-base, --boot-base, --boot-accent,
// --hands-base, --hands-accent, --wand-accent) actually took. These are
// the shipped product's own colours -- the rig draws a summoned wizard's
// palette from this pool (deterministically, from its identity) rather
// than inventing colour. The portraits' occasional --collar-accent slot
// has no matching named group in the shape library and is not used.

export const PALETTE_POOL = Object.freeze({
  hatBase: ['#2B2B2B', '#7D56ED', '#8F5CE0', '#A66EFF', '#FF88F9', '#FFFFFF'],
  hatAccent: ['#3DADEA', '#3FE04B', '#5AF99A', '#66EDFF', '#6EFFF8', '#84FF61', '#A66EFF', '#E53535', '#FF4848', '#FF526F', '#FF88F9', '#FFC200', '#FFFFFF'],
  medallionBase: ['#6EFFF8', '#84FF61', '#A66EFF', '#FF4848', '#FF88F9', '#FFC200', '#FFFFFF'],
  collarBase: ['#2B2B2B', '#3DADEA', '#3FE04B', '#66EDFF', '#6EFFF8', '#7D56ED', '#84FF61', '#8F5CE0', '#A66EFF', '#E53535', '#FF4848', '#FF526F', '#FF88F9', '#FFFFFF'],
  capeBase: ['#2B2B2B', '#5AF99A', '#66EDFF', '#A66EFF', '#D8A53F', '#FF4848', '#FFFCD6', '#FFFFFF'],
  pantsBase: ['#2B2B2B', '#3DADEA', '#3FE04B', '#5A7B84', '#7D56ED', '#808080', '#8F5CE0', '#BFCBD1', '#E53535', '#FF88F9', '#FFEF57', '#FFFFFF'],
  bootBase: ['#2B2B2B', '#5AF99A', '#66EDFF', '#9B4F40', '#A66EFF', '#FF4848', '#FFFFFF'],
  bootAccent: ['#2B2B2B', '#3DADEA', '#565656', '#66EDFF', '#6EFFF8', '#84FF61', '#A66EFF', '#C17D49', '#FF4848', '#FF526F', '#FF85A5', '#FF88F9', '#FFFFFF'],
  handsBase: ['#2B2B2B', '#FFFFFF'],
  handsAccent: ['#2B2B2B', '#3DADEA', '#3FE04B', '#66EDFF', '#6EFFF8', '#7D56ED', '#84FF61', '#8F5CE0', '#A66EFF', '#E53535', '#F4C356', '#FF4848', '#FF526F', '#FF88F9', '#FFFFFF'],
  wandAccent: ['#3DADEA', '#3FE04B', '#5AF99A', '#66EDFF', '#6EFFF8', '#84FF61', '#8F5CE0', '#A66EFF', '#E53535', '#FF4848', '#FF526F', '#FF88F9'],
});

export const PALETTE_SLOTS = Object.freeze(Object.keys(PALETTE_POOL));
