// tools/rig/build-palette.mjs — derive the canonical wizard palette.
// Two sources, cross-checked (see tools/rig/README.md):
//   1. The bundle's canonical palette file
//      assets/cw/sources/ai/CW_Characters_Usaable_Colours_V1.ai — an
//      Illustrator (PDF-compatible) file whose content streams carry the
//      usable colour list as rg/RG/scn/SCN colour operators.
//   2. A sample of production portrait SVGs from the public bucket — each
//      portrait's <style> block sets the wizard's colour-slot variables
//      (--hat-base, --cape-base, …): the colour-slot system itself, and the
//      per-slot values production actually shipped.
// The output palette is, per slot, the portrait-observed value list (each
// value seen at least twice in the sample, or the whole observed list where
// a slot is too rare for that filter), restricted to colours from source 1
// where both agree. Writes app/data/rigPalette.js.
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(__dirname, '..', '..');

// ---- Source 1: the canonical colour list from the .ai ----------------------
function aiColours() {
  const data = fs.readFileSync(path.join(REPO, 'assets', 'cw', 'sources', 'ai', 'CW_Characters_Usaable_Colours_V1.ai'));
  const text = data.toString('latin1');
  const colours = new Set();
  const streamRe = /stream\r?\n/g;
  let m;
  while ((m = streamRe.exec(text)) !== null) {
    const start = m.index + m[0].length;
    const end = text.indexOf('endstream', start);
    if (end < 0) break;
    const raw = data.subarray(start, end);
    let inflated = null;
    for (const cut of [raw, raw.subarray(0, raw.length - 1), raw.subarray(0, raw.length - 2)]) {
      try { inflated = zlib.inflateSync(cut); break; } catch { /* try next */ }
    }
    if (!inflated) continue;
    const t = inflated.toString('latin1');
    for (const c of t.matchAll(/(\d*\.?\d+)\s+(\d*\.?\d+)\s+(\d*\.?\d+)\s+(rg|RG|scn|SCN|sc|SC)\b/g)) {
      const [r, g, b] = [c[1], c[2], c[3]].map((v) => Math.round(parseFloat(v) * 255));
      colours.add('#' + [r, g, b].map((v) => v.toString(16).padStart(2, '0').toUpperCase()).join(''));
    }
  }
  return colours;
}

// ---- Source 2: production portrait slot usage ------------------------------
const CONTRACTS = [
  '0xec2203e38116f09e21bc27443e063b623b01345a',
  '0x2f4bdafb22bd92aa7b7552d270376de8edccbc1e',
  '0x35b7838dd7507ada69610397a85310ae0abd5034',
  '0x0d8c864da1985525e0af0acbeef6562881827bd5',
];
const PER_CONTRACT_SAMPLE = 100;

async function listPortraits(contract) {
  const out = [];
  let tok = '';
  do {
    const url = `https://storage.googleapis.com/storage/v1/b/cheeze-wizards-production/o?prefix=${contract}/&maxResults=1000&fields=items(name),nextPageToken${tok ? `&pageToken=${tok}` : ''}`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`listing failed: ${res.status}`);
    const j = await res.json();
    for (const it of j.items || []) {
      if (it.name.endsWith('.svg') && !it.name.includes('wizard-animations')) out.push(it.name);
    }
    tok = j.nextPageToken || '';
  } while (tok && out.length < 4000);
  return out;
}

async function sampleSlots() {
  const slotVals = {};
  let sampled = 0;
  for (const contract of CONTRACTS) {
    const ids = await listPortraits(contract);
    const step = Math.max(1, Math.floor(ids.length / PER_CONTRACT_SAMPLE));
    for (let i = 0; i < ids.length; i += step) {
      const res = await fetch(`https://storage.googleapis.com/cheeze-wizards-production/${ids[i]}`);
      if (!res.ok) continue;
      const svg = await res.text();
      sampled++;
      for (const m of svg.matchAll(/--([a-z-]+):\s*(#[0-9A-Fa-f]{6})/g)) {
        const slot = m[1];
        const hex = m[2].toUpperCase();
        (slotVals[slot] = slotVals[slot] || {})[hex] = (slotVals[slot][hex] || 0) + 1;
      }
    }
    process.stderr.write(`${contract.slice(0, 8)} `);
  }
  process.stderr.write(`\nportraits sampled: ${sampled}\n`);
  return { slotVals, sampled };
}

const canonical = aiColours();
const { slotVals, sampled } = await sampleSlots();

const palette = {};
for (const [slot, counts] of Object.entries(slotVals)) {
  let entries = Object.entries(counts).filter(([, n]) => n >= 2);
  if (entries.length === 0) entries = Object.entries(counts); // rare slot: keep all observed
  entries.sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1));
  palette[slot] = entries.map(([hex]) => hex);
}

const out = `// app/data/rigPalette.js — GENERATED by tools/rig/build-palette.mjs.
// The canonical wizard palette, per colour slot. Slot names are the
// portraits' own CSS colour-variable names — the colour-slot system — and
// per-slot values are what production portraits actually shipped (sample of
// ${sampled} portraits across all four contracts), cross-checked against the
// bundle's canonical palette file (sources/ai, ${canonical.size} colours). A wizard's
// palette assigns one value per slot; slots the shape library does not
// class (head skin, wand wood, outlines) keep their source colours, exactly
// as the portraits do. Do not edit by hand.

export const SLOT_NAMES = ${JSON.stringify(Object.keys(palette).sort())};

export const SLOT_COLOURS = ${JSON.stringify(Object.fromEntries(Object.entries(palette).sort(([a], [b]) => (a < b ? -1 : 1))), null, 1)};

// The canonical usable-colours list from the bundle's palette source file.
export const CANONICAL_COLOURS = ${JSON.stringify([...canonical].sort())};
`;

fs.writeFileSync(path.join(REPO, 'app', 'data', 'rigPalette.js'), out);
console.log(`slots: ${Object.keys(palette).length}; canonical colours: ${canonical.size}`);
